//Generated by GetAllHeaderLinks - header-links
export const links = [
  { id: 0, name: "Home", href: "/" },
  //Generated by GetModelHeaderLinkItem - header link item
  { id: "candidates", name: "Candidates", href: "/candidates" },
  //Generated by GetModelHeaderLinkItem - header link item
  { id: "providers", name: "Providers", href: "/providers" },
  //Generated by GetModelHeaderLinkItem - header link item
  { id: "states", name: "States", href: "/states" },
  //Generated by GetModelHeaderLinkItem - header link item
  {
    id: "employer-offices",
    name: "Employer Offices",
    href: "/employer-offices",
  },
  //Generated by GetModelHeaderLinkItem - header link item
  { id: "divisions", name: "Divisions", href: "/divisions" },
  //Generated by GetModelHeaderLinkItem - header link item
  { id: "positions", name: "Positions", href: "/positions" },
  //Generated by GetModelHeaderLinkItem - header link item
  { id: "stages", name: "Stages", href: "/stages" },
  //Generated by GetModelHeaderLinkItem - header link item
  { id: "statuses", name: "Status", href: "/statuses" },
  //Generated by GetModelHeaderLinkItem - header link item
  { id: "group-sites", name: "Group Sites", href: "/group-sites" },
  //Generated by GetModelHeaderLinkItem - header link item
  {
    id: "provider-sources",
    name: "Provider Sources",
    href: "/provider-sources",
  },
  //Generated by GetModelHeaderLinkItem - header link item
  { id: "priorities", name: "Priorities", href: "/priorities" },
  //Generated by GetModelHeaderLinkItem - header link item
  {
    id: "placement-status",
    name: "Placement Status",
    href: "/placement-status",
  },
  //Generated by GetModelHeaderLinkItem - header link item
  { id: "provider-types", name: "Provider Types", href: "/provider-types" },
  //Generated by GetModelHeaderLinkItem - header link item
  { id: "tracking-status", name: "Tracking Status", href: "/tracking-status" },
];
