//Generated by WriteToModelsPage - Model Page Sidebar
import React from "react";
import StatusFilterForm from "@/components/statuses/StatusFilterForm";
import StatusTable from "@/components/statuses/StatusTable";

export const metadata = {
  title: "Status",
};

const Status: React.FC = () => {
  return (
    <div className="flex flex-col flex-1 w-full px-4 mx-auto text-sm lg:px-0 main-height-less-footer">
      <div className="flex flex-col flex-1 w-[740px] mx-auto gap-4 p-4 border rounded-sm border-border">
        <h1 className="text-2xl font-bold">Status</h1>
        <div className="flex">
          <StatusFilterForm />
        </div>
        <div className="flex flex-col flex-1 ">
          <StatusTable />
        </div>
      </div>
    </div>
  );
};

export default Status;
