//Generated by WriteToMultiRoute_ts - multi route.ts
import sequelize from "@/config/db";
import { createProviderSource, updateProviderSource } from "@/utils/api/ProviderSourceLibs";
import { ProviderSourceUpdatePayload } from "@/interfaces/ProviderSourceInterfaces";
import { ProviderSourceSchema } from "@/schema/ProviderSourceSchema";
import { PRIMARY_KEY, UNIQUE_FIELDS } from "@/utils/constants/ProviderSourceConstants";
import handleSequelizeError from "@/utils/errorHandling";
import { checkDuplicateCombinations, returnJSONResponse } from "@/utils/utils";
import { NextResponse } from "next/server";

//Generated by GetMultiCreateModelPOSTRoute - GetMultiCreateModelPOSTRoute
export const POST = async (req: Request) => {
  const body = (await req.json()) as ProviderSourceUpdatePayload;
  const { ProviderSources } = body;

  //Generated by GenerateUniquenessValidation
  //Validate record uniqueness

  UNIQUE_FIELDS.forEach((item) => {
    const uniquenessError = checkDuplicateCombinations(item, ProviderSources);

    if (uniquenessError) {
      return returnJSONResponse({
        status: "error",
        error: uniquenessError,
        errorCode: 422,
      });
    }
  });

  const t = await sequelize.transaction();
  let recordsCreated = 0;

  for (const item of ProviderSources) {
    try {
      await ProviderSourceSchema.validate(item);
    } catch (error) {
      return handleSequelizeError(error);
    }
  }

  try {
    for (const item of ProviderSources) {
      if (item[PRIMARY_KEY] === "") {
        await createProviderSource(item, t);
        recordsCreated++;
      } else {
        await updateProviderSource(item, PRIMARY_KEY, t);
      }
    }

    await t.commit();

    return NextResponse.json({
      recordsCreated,
    });
  } catch (err) {
    await t.rollback();
    return handleSequelizeError(err);
  }
};;
