//Generated by GetuseModelListts - useModelList.ts
"use client";
import { GetPlacementStatusResponse } from "@/interfaces/PlacementStatusInterfaces";
import { PlacementStatusSearchParams } from "@/interfaces/PlacementStatusInterfaces";
import { BasicModel } from "@/interfaces/GeneralInterfaces";
import axiosClient from "@/utils/api";
import { useQuery } from "@tanstack/react-query";
import { useEffect, useState } from "react";

const getPlacementStatus = async () => {
  const { data } = await axiosClient.get<GetPlacementStatusResponse>(`placement-status`, {
    params: {
      fetchCount: "false",
      simpleOnly: "true",
    } as Partial<PlacementStatusSearchParams>,
  });

  return data.rows.map((item) => ({
    id: item.id,
    name: item.name,
  }));
};

interface UseListProps {
  placeholderData?: BasicModel[];
}

const usePlacementStatusList = (prop?: UseListProps) => {
  //local states
  const [mounted, setMounted] = useState(false);

  const _ = useQuery({
    queryKey: ["placementStatus-list"],
    queryFn: getPlacementStatus,
    enabled: mounted,
    placeholderData: prop?.placeholderData,
  });

  useEffect(() => {
    setMounted(true);
  }, []);

  return _;
};

export default usePlacementStatusList;
