//Generated by GetuseModelListts - useModelList.ts
"use client";
import { GetGroupSitesResponse } from "@/interfaces/GroupSiteInterfaces";
import { GroupSiteSearchParams } from "@/interfaces/GroupSiteInterfaces";
import { BasicModel } from "@/interfaces/GeneralInterfaces";
import axiosClient from "@/utils/api";
import { useQuery } from "@tanstack/react-query";
import { useEffect, useState } from "react";

const getGroupSites = async () => {
  const { data } = await axiosClient.get<GetGroupSitesResponse>(`group-sites`, {
    params: {
      fetchCount: "false",
      simpleOnly: "true",
    } as Partial<GroupSiteSearchParams>,
  });

  return data.rows.map((item) => ({
    id: item.id,
    name: item.name,
  }));
};

interface UseListProps {
  placeholderData?: BasicModel[];
}

const useGroupSiteList = (prop?: UseListProps) => {
  //local states
  const [mounted, setMounted] = useState(false);

  const _ = useQuery({
    queryKey: ["groupSite-list"],
    queryFn: getGroupSites,
    enabled: mounted,
    placeholderData: prop?.placeholderData,
  });

  useEffect(() => {
    setMounted(true);
  }, []);

  return _;
};

export default useGroupSiteList;
