//Generated by GeneratePageFile
import { FormikCheckbox } from "@/components/formik/FormikCheckbox";
import { FormikCombobox } from "@/components/formik/FormikCombobox";
import { FormikDate } from "@/components/formik/FormikDate";
import { FormikDateAndTime } from "@/components/formik/FormikDateAndTime";
import { FormikDatePicker } from "@/components/formik/FormikDatePicker";
import { FormikFacetedControl } from "@/components/formik/FormikFacetedControl";
import { FormikFileInput } from "@/components/formik/FormikFileInput";
import { FormikInput } from "@/components/formik/FormikInput";
import { FormikSelect } from "@/components/formik/FormikSelect";
import {
  FormikSwitch,
  FormikSwitchProps,
} from "@/components/formik/FormikSwitch";
import { FormikTextArea } from "@/components/formik/FormikTextArea";
import { BasicModel } from "@/interfaces/GeneralInterfaces";
import { ClassValue } from "clsx";
import React, { RefObject, forwardRef } from "react";

interface ControlProps {
  name: string;
  label?: string;
  submitOnChange?: boolean;
  placeholder?: string;
  containerClassNames?: ClassValue[];
  disabled?: boolean;
  setHasUpdate?: () => void;
  ref?: RefObject<any> | undefined;
}

interface TextProps extends ControlProps {
  type: "Text";
  setFocusOnLoad?: boolean;
}

interface DateProps extends ControlProps {
  type: "Date";
}

interface FileInputProps extends ControlProps {
  type: "FileInput";
}

interface DecimalProps extends ControlProps {
  type: "Decimal";
}

interface CurrencyProps extends ControlProps {
  type: "Currency";
  currency: string;
}

interface DateAndTimeProps extends ControlProps {
  type: "DateAndTime";
}

interface TextareaProps extends ControlProps {
  type: "Textarea";
}

interface DatePickerProps extends ControlProps {
  type: "DatePicker";
}

interface WholeNumberProps extends ControlProps {
  type: "WholeNumber";
}

interface SwitchProps extends ControlProps {
  type: "Switch";
  size?: FormikSwitchProps["size"];
}

interface ComboBoxProps extends ControlProps {
  type: "ComboBox";
  options: BasicModel[];
  showLabel: boolean;
}

interface SelectProps extends ControlProps {
  type: "Select";
  options: BasicModel[];
  showLabel: boolean;
  allowBlank?: boolean;
}

interface FacetedControlProps extends ControlProps {
  type: "FacetedControl";
  options: BasicModel[];
  limit?: number;
}

interface CheckboxProps extends ControlProps {
  type: "Checkbox";
}

type FormikControlProps =
  | FacetedControlProps
  | TextProps
  | SwitchProps
  | ComboBoxProps
  | SelectProps
  | WholeNumberProps
  | TextareaProps
  | CheckboxProps
  | DatePickerProps
  | DateAndTimeProps
  | DateProps
  | DecimalProps
  | CurrencyProps
  | FileInputProps;

const FormikControl = forwardRef<any, FormikControlProps>((props, ref) => {
  const {
    type,
    name,
    label = "",
    submitOnChange,
    containerClassNames,
    placeholder,
  } = props;
  switch (type) {
    case "Switch":
      return (
        <FormikSwitch
          name={name}
          label={label}
          submitOnChange={submitOnChange}
          containerClassNames={containerClassNames}
          size={props.size || undefined}
          setHasUpdate={props.setHasUpdate}
        />
      );
    case "FacetedControl":
      return (
        <FormikFacetedControl
          name={name}
          options={props.options}
          label={label}
          containerClassNames={containerClassNames}
          limit={props.limit || 4}
          setHasUpdate={props.setHasUpdate}
        />
      );
    case "ComboBox":
      return (
        <FormikCombobox
          name={name}
          items={props.options}
          label={label}
          containerClassNames={containerClassNames}
          showLabel={props.showLabel}
          setHasUpdate={props.setHasUpdate}
        />
      );
    case "Select":
      return (
        <FormikSelect
          name={name}
          options={props.options}
          label={label}
          containerClassNames={containerClassNames}
          showLabel={props.showLabel}
          allowBlank={props.allowBlank || false}
          setHasUpdate={props.setHasUpdate}
        />
      );
    case "Textarea":
      return (
        <FormikTextArea
          name={name}
          label={label}
          containerClassNames={containerClassNames}
          setHasUpdate={props.setHasUpdate}
        />
      );
    case "WholeNumber":
      return (
        <FormikInput
          name={name}
          label={label}
          isNumeric={true}
          wholeNumberOnly={true}
          containerClassNames={containerClassNames}
          setHasUpdate={props.setHasUpdate}
        />
      );
    case "Decimal":
      return (
        <FormikInput
          name={name}
          label={label}
          isNumeric={true}
          wholeNumberOnly={false}
          containerClassNames={containerClassNames}
          setHasUpdate={props.setHasUpdate}
        />
      );
    case "Checkbox":
      return (
        <FormikCheckbox
          name={name}
          label={label}
          containerClassNames={containerClassNames}
          setHasUpdate={props.setHasUpdate}
        />
      );
    case "DatePicker":
      return (
        <FormikDatePicker
          name={name}
          label={label}
          containerClassNames={containerClassNames}
          setHasUpdate={props.setHasUpdate}
        />
      );
    case "DateAndTime":
      return (
        <FormikDateAndTime
          name={name}
          label={label}
          containerClassNames={containerClassNames}
          setHasUpdate={props.setHasUpdate}
        />
      );
    case "Date":
      return (
        <FormikDate
          name={name}
          label={label}
          containerClassNames={containerClassNames}
          setHasUpdate={props.setHasUpdate}
        />
      );
    case "Currency":
      return (
        <FormikInput
          name={name}
          label={label}
          isNumeric={true}
          wholeNumberOnly={false}
          containerClassNames={containerClassNames}
          setHasUpdate={props.setHasUpdate}
          currency={props.currency}
        />
      );
    case "FileInput":
      return (
        <FormikFileInput
          name={name}
          setHasUpdate={props.setHasUpdate}
          label={label}
        />
      );
    default:
      return (
        <FormikInput
          name={name}
          label={label}
          submitOnChange={submitOnChange}
          placeholder={placeholder}
          containerClassNames={containerClassNames}
          ref={ref}
          setFocusOnLoad={props.setFocusOnLoad}
          disabled={props.disabled}
          setHasUpdate={props.setHasUpdate}
        />
      );
  }
});

export default FormikControl;
