//Generated by WriteToModelfilterform_tsx - ModelFilterForm.tsx
"use client";
import { usePriorityStore } from "@/hooks/priorities/usePriorityStore";
import {
  PriorityFormikFilter,
  PrioritySearchParams,
} from "@/interfaces/PriorityInterfaces";
import { DEFAULT_LIMIT } from "@/utils/constants";
import { getFilterValueFromURL, getParamsObject } from "@/utils/utilities";
import { encodeParams } from "@/utils/utils";
import { Form, Formik, FormikHelpers, FormikProps } from "formik";
import React, { MouseEventHandler } from "react";
import { DEFAULT_FILTERS,CONTROL_OPTIONS, } from "@/utils/constants/PriorityConstants";
import LimitSelector from "@/components/form/LimitSelector";
import { useURL } from "@/hooks/useURL";
import FormikControl from "@/components/form/FormikControl";
import { Button } from "@/components/ui/Button";
import { isEqual } from "lodash";
//Generated by ImportAllUseModelListHookBySeqModel


const PriorityFilterForm: React.FC = () => {
  const { router, query, pathname } = useURL<PrioritySearchParams>();

  //SearchParams Variables
  const limit = query["limit"] || DEFAULT_LIMIT;

  const defaultFilters = DEFAULT_FILTERS;
  const initialValues: PriorityFormikFilter = getFilterValueFromURL(
    query,
    defaultFilters
  );

  //Tanstack queries
  //Generated by GetRequiredQueryFromTanstackBySeqModel


  //Zustand stores
  const [setPage, setLastPage, setFetchCount, resetRowSelection, setCursor] = usePriorityStore(
    (state) => [
      state.setPage,
      state.setLastPage,
      state.setFetchCount,
      state.resetRowSelection,
      state.setCursor,
    ]
  );

  const handleFormikSubmit = (
    values: Partial<PriorityFormikFilter>,
    formik: FormikHelpers<PriorityFormikFilter>
  ) => {
    const params = {
      ...query,
      ...(getParamsObject(values, defaultFilters) as Partial<PrioritySearchParams>),
    };

    const newURL = `${pathname}?${encodeParams(params)}`;
    router.push(newURL);
    setFetchCount(true);
    resetRowSelection();
  };

  const handleLimitChange = (value: string) => {
    const params = { ...query, limit: value };
    const newURL = `${pathname}?${encodeParams(params)}`;
    router.push(newURL);
    resetRowSelection();
  };

  const renderFormik = (formik: FormikProps<PriorityFormikFilter>) => {

const filtered = isEqual(defaultFilters, formik.values);

    const handleSubmitClick: MouseEventHandler = (e) => {
      e.preventDefault();
      formik.submitForm();
    };

    const handleClearClick: MouseEventHandler = (e) => {
      e.preventDefault();
      formik.setValues(defaultFilters as PriorityFormikFilter);
formik.submitForm();
    };


    return (
      <Form className="flex gap-2 w-[750px]" autoComplete="off">
        {/* Generated by GetFormikFilterQControl - GetFormikFilterQControl */}
<FormikControl
  name="q"
  placeholder="Filter Priorities..."
  type="Text"
  containerClassNames={["w-[250px]"]}
/>
        {/* Generated by GetAllFormikFilterControlBySeqModel */}
<Button
          type="button"
          onClick={handleSubmitClick}
          size={"sm"}
          variant={"secondary"}
        >
          Search
        </Button>
        <Button
          type="button"
          size={"sm"}
          variant={"ghost"}
          disabled={filtered}
          onClick={handleClearClick}
        >
          Clear
        </Button>
      </Form>
    );
  };

  return (
    <div className="flex justify-between w-full">
      <Formik
        initialValues={initialValues}
        onSubmit={handleFormikSubmit}
      >
        {renderFormik}
      </Formik>
      <LimitSelector
        handleLimitChange={handleLimitChange}
        value={limit}
      />
    </div>
  );
};

export default PriorityFilterForm;
