//Generated by WriteToModelsPage - Model Page Sidebar
import React from "react";
import PositionFilterForm from "@/components/positions/PositionFilterForm";
import PositionTable from "@/components/positions/PositionTable";

export const metadata = {
  title: "Positions",
};

const Positions: React.FC = () => {
  return (
    <div className="flex flex-col flex-1 w-full px-4 mx-auto text-sm lg:px-0 main-height-less-footer">
      <div className="flex flex-col flex-1 w-[740px] mx-auto gap-4 p-4 border rounded-sm border-border">
        <h1 className="text-2xl font-bold">Positions</h1>
        <div className="flex">
          <PositionFilterForm />
        </div>
        <div className="flex flex-col flex-1 ">
          <PositionTable />
        </div>
      </div>
    </div>
  );
};

export default Positions;
