//Generated by WriteToModelsPage - Model Page Sidebar
import React from "react";
import StateFilterForm from "@/components/states/StateFilterForm";
import StateTable from "@/components/states/StateTable";

export const metadata = {
  title: "States",
};

const States: React.FC = () => {
  return (
    <div className="flex flex-col flex-1 w-full px-4 mx-auto text-sm lg:px-0 main-height-less-footer">
      <div className="flex flex-col flex-1 w-[740px] mx-auto gap-4 p-4 border rounded-sm border-border">
        <h1 className="text-2xl font-bold">States</h1>
        <div className="flex">
          <StateFilterForm />
        </div>
        <div className="flex flex-col flex-1 ">
          <StateTable />
        </div>
      </div>
    </div>
  );
};

export default States;
