//Generated by WriteToModellibs_ts - ModelLibs.ts
import { GroupSiteFormikShape } from "@/interfaces/GroupSiteInterfaces";
import { GroupSite } from "@/models/GroupSiteModel";
import { Op } from "sequelize";
import { Transaction } from "sequelize";

//Reusable functions
export const createGroupSite = async (
  groupSite: Omit<GroupSiteFormikShape, "touched" | "index" | "id">,
  t: Transaction
) => {
  return await GroupSite.create(
    {
      //Generated by GetAllFieldsToUpdateBySeqModel
name: groupSite.name!
    },
    { transaction: t }
  );
};

export const updateGroupSite = async (
  groupSite: Omit<GroupSiteFormikShape, "touched" | "index">,
  primaryKey: keyof Omit<GroupSiteFormikShape, "touched" | "index">,
  t: Transaction,
  primaryKeyValue?: string | number
) => {
  await GroupSite.update(
    {
      //Generated by GetAllFieldsToUpdateBySeqModel
name: groupSite.name!
    },
    {
      where: { [primaryKey]: primaryKeyValue || groupSite[primaryKey] },
      transaction: t,
      individualHooks: true,
    }
  );
};

export const deleteGroupSites = async (
  primaryKey: keyof Omit<GroupSiteFormikShape, "touched">,
  deletedIds: string[] | number[],
  t: Transaction
) => {
  await GroupSite.destroy({
    where: { [primaryKey]: { [Op.in]: deletedIds } },
    transaction: t,
  });
};
