//Generated by WriteToModellibs_ts - ModelLibs.ts
import { ProviderTypeFormikShape } from "@/interfaces/ProviderTypeInterfaces";
import { ProviderType } from "@/models/ProviderTypeModel";
import { Op } from "sequelize";
import { Transaction } from "sequelize";

//Reusable functions
export const createProviderType = async (
  providerType: Omit<ProviderTypeFormikShape, "touched" | "index" | "id">,
  t: Transaction
) => {
  return await ProviderType.create(
    {
      //Generated by GetAllFieldsToUpdateBySeqModel
name: providerType.name!
    },
    { transaction: t }
  );
};

export const updateProviderType = async (
  providerType: Omit<ProviderTypeFormikShape, "touched" | "index">,
  primaryKey: keyof Omit<ProviderTypeFormikShape, "touched" | "index">,
  t: Transaction,
  primaryKeyValue?: string | number
) => {
  await ProviderType.update(
    {
      //Generated by GetAllFieldsToUpdateBySeqModel
name: providerType.name!
    },
    {
      where: { [primaryKey]: primaryKeyValue || providerType[primaryKey] },
      transaction: t,
      individualHooks: true,
    }
  );
};

export const deleteProviderTypes = async (
  primaryKey: keyof Omit<ProviderTypeFormikShape, "touched">,
  deletedIds: string[] | number[],
  t: Transaction
) => {
  await ProviderType.destroy({
    where: { [primaryKey]: { [Op.in]: deletedIds } },
    transaction: t,
  });
};
