//Generated by WriteToModellibs_ts - ModelLibs.ts
import { StatusFormikShape } from "@/interfaces/StatusInterfaces";
import { Status } from "@/models/StatusModel";
import { Op } from "sequelize";
import { Transaction } from "sequelize";

//Reusable functions
export const createStatus = async (
  status: Omit<StatusFormikShape, "touched" | "index" | "id">,
  t: Transaction
) => {
  return await Status.create(
    {
      //Generated by GetAllFieldsToUpdateBySeqModel
name: status.name!
    },
    { transaction: t }
  );
};

export const updateStatus = async (
  status: Omit<StatusFormikShape, "touched" | "index">,
  primaryKey: keyof Omit<StatusFormikShape, "touched" | "index">,
  t: Transaction,
  primaryKeyValue?: string | number
) => {
  await Status.update(
    {
      //Generated by GetAllFieldsToUpdateBySeqModel
name: status.name!
    },
    {
      where: { [primaryKey]: primaryKeyValue || status[primaryKey] },
      transaction: t,
      individualHooks: true,
    }
  );
};

export const deleteStatus = async (
  primaryKey: keyof Omit<StatusFormikShape, "touched">,
  deletedIds: string[] | number[],
  t: Transaction
) => {
  await Status.destroy({
    where: { [primaryKey]: { [Op.in]: deletedIds } },
    transaction: t,
  });
};
