//Generated by WriteToModellibs_ts - ModelLibs.ts
import { StateFormikShape } from "@/interfaces/StateInterfaces";
import { State } from "@/models/StateModel";
import { Op } from "sequelize";
import { Transaction } from "sequelize";

//Reusable functions
export const createState = async (
  state: Omit<StateFormikShape, "touched" | "index" | "id">,
  t: Transaction
) => {
  return await State.create(
    {
      //Generated by GetAllFieldsToUpdateBySeqModel
name: state.name!
    },
    { transaction: t }
  );
};

export const updateState = async (
  state: Omit<StateFormikShape, "touched" | "index">,
  primaryKey: keyof Omit<StateFormikShape, "touched" | "index">,
  t: Transaction,
  primaryKeyValue?: string | number
) => {
  await State.update(
    {
      //Generated by GetAllFieldsToUpdateBySeqModel
name: state.name!
    },
    {
      where: { [primaryKey]: primaryKeyValue || state[primaryKey] },
      transaction: t,
      individualHooks: true,
    }
  );
};

export const deleteStates = async (
  primaryKey: keyof Omit<StateFormikShape, "touched">,
  deletedIds: string[] | number[],
  t: Transaction
) => {
  await State.destroy({
    where: { [primaryKey]: { [Op.in]: deletedIds } },
    transaction: t,
  });
};
