//Generated by WriteToModellibs_ts - ModelLibs.ts
import { TrackingStatusFormikShape } from "@/interfaces/TrackingStatusInterfaces";
import { TrackingStatus } from "@/models/TrackingStatusModel";
import { Op } from "sequelize";
import { Transaction } from "sequelize";

//Reusable functions
export const createTrackingStatus = async (
  trackingStatus: Omit<TrackingStatusFormikShape, "touched" | "index" | "id">,
  t: Transaction
) => {
  return await TrackingStatus.create(
    {
      //Generated by GetAllFieldsToUpdateBySeqModel
name: trackingStatus.name!
    },
    { transaction: t }
  );
};

export const updateTrackingStatus = async (
  trackingStatus: Omit<TrackingStatusFormikShape, "touched" | "index">,
  primaryKey: keyof Omit<TrackingStatusFormikShape, "touched" | "index">,
  t: Transaction,
  primaryKeyValue?: string | number
) => {
  await TrackingStatus.update(
    {
      //Generated by GetAllFieldsToUpdateBySeqModel
name: trackingStatus.name!
    },
    {
      where: { [primaryKey]: primaryKeyValue || trackingStatus[primaryKey] },
      transaction: t,
      individualHooks: true,
    }
  );
};

export const deleteTrackingStatus = async (
  primaryKey: keyof Omit<TrackingStatusFormikShape, "touched">,
  deletedIds: string[] | number[],
  t: Transaction
) => {
  await TrackingStatus.destroy({
    where: { [primaryKey]: { [Op.in]: deletedIds } },
    transaction: t,
  });
};
