//Generated by WriteToLayout_tsx - GenerateMainLayoutSidebar
import Footer from "@/components/Footer";
import Header from "@/components/header/Header";
import "./globals.css";
import { Roboto } from "next/font/google";
import ClientProviders from "@/components/ClientProviders";
import SessionButton from "@/components/header/SessionButton";
import Providers from "@/components/ThemeProvider";
import Sidebar from "@/components/sidebar/Sidebar";

const inter = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  fallback: ["system-ui", "arial"],
});

export const metadata = {
  title: "threesixty",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${inter.className} dark`}
    >
      <body className="flex w-full min-h-screen">
        <Providers>
          <ClientProviders>
            <Sidebar />
            <main className="flex flex-col flex-1 pt-4 pl-0 pr-4">
              {children}
              <Footer />
            </main>
          </ClientProviders>
        </Providers>
      </body>
    </html>
  );
}
