//Generated by GeneratePageFile
import React from "react";

const Page: React.FC = () => {
  return (
    <div className="flex flex-col justify-center flex-1 w-full max-w-screen-lg px-4 mx-auto md:px-0">
      Page
    </div>
  );
};

export default Page;
