//Generated by WriteToMultiRoute_ts - multi route.ts
import sequelize from "@/config/db";
import { createTrackingStatus, updateTrackingStatus } from "@/utils/api/TrackingStatusLibs";
import { TrackingStatusUpdatePayload } from "@/interfaces/TrackingStatusInterfaces";
import { TrackingStatusSchema } from "@/schema/TrackingStatusSchema";
import { PRIMARY_KEY, UNIQUE_FIELDS } from "@/utils/constants/TrackingStatusConstants";
import handleSequelizeError from "@/utils/errorHandling";
import { checkDuplicateCombinations, returnJSONResponse } from "@/utils/utils";
import { NextResponse } from "next/server";

//Generated by GetMultiCreateModelPOSTRoute - GetMultiCreateModelPOSTRoute
export const POST = async (req: Request) => {
  const body = (await req.json()) as TrackingStatusUpdatePayload;
  const { TrackingStatus } = body;

  //Generated by GenerateUniquenessValidation
  //Validate record uniqueness

  UNIQUE_FIELDS.forEach((item) => {
    const uniquenessError = checkDuplicateCombinations(item, TrackingStatus);

    if (uniquenessError) {
      return returnJSONResponse({
        status: "error",
        error: uniquenessError,
        errorCode: 422,
      });
    }
  });

  const t = await sequelize.transaction();
  let recordsCreated = 0;

  for (const item of TrackingStatus) {
    try {
      await TrackingStatusSchema.validate(item);
    } catch (error) {
      return handleSequelizeError(error);
    }
  }

  try {
    for (const item of TrackingStatus) {
      if (item[PRIMARY_KEY] === "") {
        await createTrackingStatus(item, t);
        recordsCreated++;
      } else {
        await updateTrackingStatus(item, PRIMARY_KEY, t);
      }
    }

    await t.commit();

    return NextResponse.json({
      recordsCreated,
    });
  } catch (err) {
    await t.rollback();
    return handleSequelizeError(err);
  }
};;
