import SignOutButton from "@/components/header/SignOutButton";
import { Button } from "@/components/ui/Button";
import { getAuthSession } from "@/lib/auth";
import Link from "next/link";

//Generated by GeneratePageFile
import React from "react";

const SessionButton: React.FC = async () => {
  const session = await getAuthSession();
  //const session = await getAuthSession();

  // Use a switch statement instead of multiple if statements
  return session?.user ? (
    <SignOutButton />
  ) : (
    <Button
      asChild
      className="rounded-full"
    >
      <Link href="/login">Login</Link>
    </Button>
  );
};

export default SessionButton;
