//Generated by WriteToFooter_tsx - Footer.tsx sidebar
import Image from "next/image";
import React from "react";

const Footer: React.FC = () => {
  return (
    <div className="h-[50px] flex items-center justify-between w-full mx-auto px-4 text-xs select-none">
      <div>&#169; 2023 Pradascus. All rights reserved.</div>
    </div>
  );
};

export default Footer;
