//Generated by GetuseModelListts - useModelList.ts
"use client";
import { GetStatesResponse } from "@/interfaces/StateInterfaces";
import { StateSearchParams } from "@/interfaces/StateInterfaces";
import { BasicModel } from "@/interfaces/GeneralInterfaces";
import axiosClient from "@/utils/api";
import { useQuery } from "@tanstack/react-query";
import { useEffect, useState } from "react";

const getStates = async (useName: boolean = false) => {
  const { data } = await axiosClient.get<GetStatesResponse>(`states`, {
    params: {
      fetchCount: "false",
      simpleOnly: "true",
    } as Partial<StateSearchParams>,
  });

  return data.rows.map((item) => ({
    id: !useName ? item.id : item.name,
    name: item.name,
  }));
};

interface UseListProps {
  placeholderData?: BasicModel[];
  useName?: boolean;
}

const useStateList = (prop?: UseListProps) => {
  //local states
  const [mounted, setMounted] = useState(false);

  const _ = useQuery({
    queryKey: ["state-list"],
    queryFn: () => getStates(prop?.useName),
    enabled: mounted,
    placeholderData: prop?.placeholderData,
  });

  useEffect(() => {
    setMounted(true);
  }, []);

  return _;
};

export default useStateList;
