//Generated by GenerateModelSyncRoute
import { NextResponse } from "next/server";
import { VerificationTokenSync } from "../../../../models/VerificationTokenModel";

export async function GET(request: Request) {
  await VerificationTokenSync();
  return NextResponse.json({ data: "success" });
}
