//Generated by WriteToModelinterface_ts - ModelInterface.ts Next 13
//Generated by GetAllRelatedInterfaceImportBySeqModel
//Generated by GetRelatedInterfaceImport - RelatedInterfaceImport
import {
  CandidateStatusFormikInitialValues,
  CandidateStatusFormikShape,
  CandidateStatusModel,
  CandidateStatusUpdatePayload,
} from "@/interfaces/CandidateStatusInterfaces";
//Generated by GetAllRelatedRightModelImport
import { ProviderModel } from "@/interfaces/ProviderInterfaces"; //Generated by GetRelatedRightModelImport - GetRelatedRightModelImport
import { ListQuery } from "./interface";

export interface CandidateModel {
  //Generated by GetAllModelFieldTypeBySeqModel
  candidateName: string; //Generated by GetModelFieldType
  source: string | null; //Generated by GetModelFieldType
  candidateState: number | string | null; //Generated by GetModelFieldType
  providerID: number | string | null; //Generated by GetModelFieldType
  providerState: number | string | null; //Generated by GetModelFieldType
  providerOffice: string | null; //Generated by GetModelFieldType
  providerSource: number | string | null; //Generated by GetModelFieldType
  providerType: number | string | null; //Generated by GetModelFieldType
  providerContactName: string | null; //Generated by GetModelFieldType
  providerEmail: string | null; //Generated by GetModelFieldType
  providerContactNumber: string | null; //Generated by GetModelFieldType
  email: string | null; //Generated by GetModelFieldType
  employer: string | null; //Generated by GetModelFieldType
  employerOffice: number | string | null; //Generated by GetModelFieldType
  employerState: number | string | null; //Generated by GetModelFieldType
  employerCandidateID: string | null; //Generated by GetModelFieldType
  employerCandidateOwner: string | null; //Generated by GetModelFieldType
  groupSite: number | string | null; //Generated by GetModelFieldType
  division: number | string | null; //Generated by GetModelFieldType
  wageSubsidyAmount: string; //Generated by GetModelFieldType
  benchmarkHours: string; //Generated by GetModelFieldType
  startDate: string; //Generated by GetModelFieldType
  stage: number | string | null; //Generated by GetModelFieldType
  outcomeReminder: string | null; //Generated by GetModelFieldType
  payslipStatus: string | null; //Generated by GetModelFieldType
  priority: number | string | null; //Generated by GetModelFieldType
  placementSent: boolean; //Generated by GetModelFieldType
  placementStatus: number | string | null; //Generated by GetModelFieldType
  archive: boolean; //Generated by GetModelFieldType
  invoiced: boolean; //Generated by GetModelFieldType
  invoiceNumber: string | null; //Generated by GetModelFieldType
  enquiryDate: string | null; //Generated by GetModelFieldType
  enquiryType: string | null; //Generated by GetModelFieldType
  wSAgreement: string | null; //Generated by GetModelFieldType
  wSSchedule: string | null; //Generated by GetModelFieldType
  notes: string | null; //Generated by GetModelFieldType
  id: number | string; //Generated by GetModelFieldType
  createdAt: string;
  updatedAt: string;
  //Generated by GetAllChildModelInterfaceBySeqModel
  CandidateStatus: CandidateStatusModel[]; //Generated by GetChildModelInterface - ChildModelInterface

  //Generated by GetAllRelatedRightModelInterface
  Provider: ProviderModel; //Generated by GetRelatedRightModelInterface - GetRelatedRightModelInterface
}

//The keys after the updatedAt is generated by GetAllRelatedModelNameBySeqModel - RelatedModelName
export interface CandidateFormikShape
  extends Omit<
    CandidateModel,
    | "slug"
    | "createdAt"
    | "updatedAt"
    | "CandidateStatus" //Generated by GetRelatedPluralizedModelName - RelatedPluralizedModelName
    | "Provider" //Generated by GetRelatedRightModelName - GetRelatedRightModelName
  > {
  touched: boolean;
  index: number;
}

//Use for continuos list form
export interface CandidateFormikInitialValues {
  Candidates: CandidateFormikShape[];
}

//The FormikInitialValues is generated by GetAllRelatedFormikInitialValues - ModelFormikInitialValue
export interface CandidateFormFormikInitialValues
  extends Omit<CandidateFormikShape, "touched" | "index"> {
  //Generated by GetAllSimpleRelatedKey
  //Generated by GetSimpleRelatedKey - GetSimpleRelatedKey
  CandidateStatus: string[] | number[];
}

//The extends portion is generated by GetModelUpdatePayloadExtension - GetRelatedPartialPayload
export interface CandidateUpdatePayload
  extends Partial<CandidateStatusUpdatePayload> {
  Candidates: Omit<CandidateFormikShape, "touched">[];
}

export interface CandidateDeletePayload {
  deletedCandidates: string[] | number[];
}

//Use for single form (with children)
//The Related Models will be replaced by the Payload version
export interface CandidateFormUpdatePayload
  extends Omit<
    CandidateFormikShape,
    | "touched"
    | "index" //Generated by GetAllSimplePluralizedFieldName
    | "CandidateStatus" //Generated by GetSimplePluralizedFieldName - GetSimplePluralizedFieldName
  > {
  //Generated by GetAllSimpleRelatedKeyPayload
  //Generated by GetSimpleRelatedKeyPayload - GetSimpleRelatedKeyPayload
  deletedCandidateStatus: string[];
  newStatus: string[];
}

export interface CandidateFormikFilter {
  //Generated by GetAllFilterInterfaceBySeqmodel
  q: string;
}

export interface CandidateSearchParams
  extends ListQuery,
    Omit<CandidateFormikFilter, ""> {
  //Generated by GetAllNonStringFilterTypes
}

export interface GetCandidatesResponse {
  count: number;
  rows: CandidateModel[];
  cursor: string;
}
