//Generated by WriteToModelinterface_ts - ModelInterface.ts Next 13

//Generated by GetAllRelatedRightModelImport
import { StateModel } from "@/interfaces/StateInterfaces";//Generated by GetRelatedRightModelImport - GetRelatedRightModelImport
import { ProviderModel } from "@/interfaces/ProviderInterfaces";//Generated by GetRelatedRightModelImport - GetRelatedRightModelImport
import { ProviderSourceModel } from "@/interfaces/ProviderSourceInterfaces";//Generated by GetRelatedRightModelImport - GetRelatedRightModelImport
import { ProviderTypeModel } from "@/interfaces/ProviderTypeInterfaces";//Generated by GetRelatedRightModelImport - GetRelatedRightModelImport
import { EmployerOfficeModel } from "@/interfaces/EmployerOfficeInterfaces";//Generated by GetRelatedRightModelImport - GetRelatedRightModelImport
import { GroupSiteModel } from "@/interfaces/GroupSiteInterfaces";//Generated by GetRelatedRightModelImport - GetRelatedRightModelImport
import { DivisionModel } from "@/interfaces/DivisionInterfaces";//Generated by GetRelatedRightModelImport - GetRelatedRightModelImport
import { StageModel } from "@/interfaces/StageInterfaces";//Generated by GetRelatedRightModelImport - GetRelatedRightModelImport
import { PriorityModel } from "@/interfaces/PriorityInterfaces";//Generated by GetRelatedRightModelImport - GetRelatedRightModelImport
import { PlacementStatusModel } from "@/interfaces/PlacementStatusInterfaces";//Generated by GetRelatedRightModelImport - GetRelatedRightModelImport
import { ListQuery } from "./interface";

export interface CandidateModel {
  //Generated by GetAllModelFieldTypeBySeqModel
candidateName: string;//Generated by GetModelFieldType
source: string | null;//Generated by GetModelFieldType
candidateStateID: number | string | null;//Generated by GetModelFieldType
providerID: number | string | null;//Generated by GetModelFieldType
providerStateID: number | string | null;//Generated by GetModelFieldType
providerOffice: string | null;//Generated by GetModelFieldType
providerSourceID: number | string | null;//Generated by GetModelFieldType
providerTypeID: number | string | null;//Generated by GetModelFieldType
providerContactName: string | null;//Generated by GetModelFieldType
providerEmail: string | null;//Generated by GetModelFieldType
providerContactNumber: string | null;//Generated by GetModelFieldType
email: string | null;//Generated by GetModelFieldType
employer: string | null;//Generated by GetModelFieldType
employerOfficeID: number | string | null;//Generated by GetModelFieldType
employerStateID: number | string | null;//Generated by GetModelFieldType
employerCandidateID: string | null;//Generated by GetModelFieldType
employerCandidateOwner: string | null;//Generated by GetModelFieldType
groupSiteID: number | string | null;//Generated by GetModelFieldType
divisionID: number | string | null;//Generated by GetModelFieldType
wageSubsidyAmount: string;//Generated by GetModelFieldType
benchmarkHours: string;//Generated by GetModelFieldType
startDate: string;//Generated by GetModelFieldType
statusID: number | string | null;//Generated by GetModelFieldType
stageID: number | string | null;//Generated by GetModelFieldType
outcomeReminder: string | null;//Generated by GetModelFieldType
payslipStatus: string | null;//Generated by GetModelFieldType
priorityID: number | string | null;//Generated by GetModelFieldType
placementSent: boolean;//Generated by GetModelFieldType
placementStatusID: number | string | null;//Generated by GetModelFieldType
archive: boolean;//Generated by GetModelFieldType
invoiced: boolean;//Generated by GetModelFieldType
invoiceNumber: string | null;//Generated by GetModelFieldType
enquiryDate: string | null;//Generated by GetModelFieldType
enquiryType: string | null;//Generated by GetModelFieldType
wSAgreement: string | null;//Generated by GetModelFieldType
wSSchedule: string | null;//Generated by GetModelFieldType
notes: string | null;//Generated by GetModelFieldType
id: number | string;//Generated by GetModelFieldType
createdAt: string;
updatedAt: string;
  
  
  //Generated by GetAllRelatedRightModelInterface
State: StateModel;//Generated by GetRelatedRightModelInterface - GetRelatedRightModelInterface
Provider: ProviderModel;//Generated by GetRelatedRightModelInterface - GetRelatedRightModelInterface
ProviderSource: ProviderSourceModel;//Generated by GetRelatedRightModelInterface - GetRelatedRightModelInterface
ProviderType: ProviderTypeModel;//Generated by GetRelatedRightModelInterface - GetRelatedRightModelInterface
EmployerOffice: EmployerOfficeModel;//Generated by GetRelatedRightModelInterface - GetRelatedRightModelInterface
GroupSite: GroupSiteModel;//Generated by GetRelatedRightModelInterface - GetRelatedRightModelInterface
Division: DivisionModel;//Generated by GetRelatedRightModelInterface - GetRelatedRightModelInterface
Stage: StageModel;//Generated by GetRelatedRightModelInterface - GetRelatedRightModelInterface
Priority: PriorityModel;//Generated by GetRelatedRightModelInterface - GetRelatedRightModelInterface
PlacementStatus: PlacementStatusModel;//Generated by GetRelatedRightModelInterface - GetRelatedRightModelInterface
}

//The keys after the updatedAt is generated by GetAllRelatedModelNameBySeqModel - RelatedModelName
export interface CandidateFormikShape extends Omit<CandidateModel, "slug" | "createdAt" | "updatedAt" 
| "State"//Generated by GetRelatedRightModelName - GetRelatedRightModelName
| "Provider"//Generated by GetRelatedRightModelName - GetRelatedRightModelName
| "ProviderSource"//Generated by GetRelatedRightModelName - GetRelatedRightModelName
| "ProviderType"//Generated by GetRelatedRightModelName - GetRelatedRightModelName
| "EmployerOffice"//Generated by GetRelatedRightModelName - GetRelatedRightModelName
| "GroupSite"//Generated by GetRelatedRightModelName - GetRelatedRightModelName
| "Division"//Generated by GetRelatedRightModelName - GetRelatedRightModelName
| "Stage"//Generated by GetRelatedRightModelName - GetRelatedRightModelName
| "Priority"//Generated by GetRelatedRightModelName - GetRelatedRightModelName
| "PlacementStatus"//Generated by GetRelatedRightModelName - GetRelatedRightModelName 
> {
  touched: boolean;
  index: number;
}

//Use for continuos list form
export interface CandidateFormikInitialValues {
  Candidates: CandidateFormikShape[];
  
}

//The FormikInitialValues is generated by GetAllRelatedFormikInitialValues - ModelFormikInitialValue
export interface CandidateFormFormikInitialValues
  extends Omit<CandidateFormikShape, "touched" | "index"> {
  
}

//The extends portion is generated by GetModelUpdatePayloadExtension - GetRelatedPartialPayload
export interface CandidateUpdatePayload  {
  Candidates: Omit<CandidateFormikShape, "touched">[];
  
}

export interface CandidateDeletePayload {
  deletedCandidates: string[] | number[];
}

//Use for single form (with children)
//The Related Models will be replaced by the Payload version
export interface CandidateFormUpdatePayload
  extends Omit<CandidateFormikShape, "touched" | "index" 
> 
 
{
  
}

export interface CandidateFormikFilter {
  //Generated by GetAllFilterInterfaceBySeqmodel
q: string
}

export interface CandidateSearchParams
  extends ListQuery,
    Omit<CandidateFormikFilter, ""> {
  //Generated by GetAllNonStringFilterTypes

}

export interface GetCandidatesResponse {
  count: number;
  rows: CandidateModel[];
  cursor: string;
}
