//Generated by WriteToModelinterface_ts - ModelInterface.ts Next 13


import { ListQuery } from "./interface";

export interface ProviderTypeModel {
  //Generated by GetAllModelFieldTypeBySeqModel
id: number | string;//Generated by GetModelFieldType
name: string;//Generated by GetModelFieldType
slug: string;
createdAt: string;
updatedAt: string;
  
  
  
}

//The keys after the updatedAt is generated by GetAllRelatedModelNameBySeqModel - RelatedModelName
export interface ProviderTypeFormikShape extends Omit<ProviderTypeModel, "slug" | "createdAt" | "updatedAt" 
 
> {
  touched: boolean;
  index: number;
}

//Use for continuos list form
export interface ProviderTypeFormikInitialValues {
  ProviderTypes: ProviderTypeFormikShape[];
  
}

//The FormikInitialValues is generated by GetAllRelatedFormikInitialValues - ModelFormikInitialValue
export interface ProviderTypeFormFormikInitialValues
  extends Omit<ProviderTypeFormikShape, "touched" | "index"> {
  
}

//The extends portion is generated by GetModelUpdatePayloadExtension - GetRelatedPartialPayload
export interface ProviderTypeUpdatePayload  {
  ProviderTypes: Omit<ProviderTypeFormikShape, "touched">[];
  
}

export interface ProviderTypeDeletePayload {
  deletedProviderTypes: string[] | number[];
}

//Use for single form (with children)
//The Related Models will be replaced by the Payload version
export interface ProviderTypeFormUpdatePayload
  extends Omit<ProviderTypeFormikShape, "touched" | "index" 
> 
 
{
  
}

export interface ProviderTypeFormikFilter {
  //Generated by GetAllFilterInterfaceBySeqmodel
q: string
}

export interface ProviderTypeSearchParams
  extends ListQuery,
    Omit<ProviderTypeFormikFilter, ""> {
  //Generated by GetAllNonStringFilterTypes

}

export interface GetProviderTypesResponse {
  count: number;
  rows: ProviderTypeModel[];
  cursor: string;
}
