//Generated by WriteToModelinterface_ts - ModelInterface.ts Next 13


import { ListQuery } from "./interface";

export interface StageModel {
  //Generated by GetAllModelFieldTypeBySeqModel
id: number | string;//Generated by GetModelFieldType
name: string;//Generated by GetModelFieldType
slug: string;
createdAt: string;
updatedAt: string;
  
  
  
}

//The keys after the updatedAt is generated by GetAllRelatedModelNameBySeqModel - RelatedModelName
export interface StageFormikShape extends Omit<StageModel, "slug" | "createdAt" | "updatedAt" 
 
> {
  touched: boolean;
  index: number;
}

//Use for continuos list form
export interface StageFormikInitialValues {
  Stages: StageFormikShape[];
  
}

//The FormikInitialValues is generated by GetAllRelatedFormikInitialValues - ModelFormikInitialValue
export interface StageFormFormikInitialValues
  extends Omit<StageFormikShape, "touched" | "index"> {
  
}

//The extends portion is generated by GetModelUpdatePayloadExtension - GetRelatedPartialPayload
export interface StageUpdatePayload  {
  Stages: Omit<StageFormikShape, "touched">[];
  
}

export interface StageDeletePayload {
  deletedStages: string[] | number[];
}

//Use for single form (with children)
//The Related Models will be replaced by the Payload version
export interface StageFormUpdatePayload
  extends Omit<StageFormikShape, "touched" | "index" 
> 
 
{
  
}

export interface StageFormikFilter {
  //Generated by GetAllFilterInterfaceBySeqmodel
q: string
}

export interface StageSearchParams
  extends ListQuery,
    Omit<StageFormikFilter, ""> {
  //Generated by GetAllNonStringFilterTypes

}

export interface GetStagesResponse {
  count: number;
  rows: StageModel[];
  cursor: string;
}
