//Generated by WriteToModelinterface_ts - ModelInterface.ts Next 13


import { ListQuery } from "./interface";

export interface StatusModel {
  //Generated by GetAllModelFieldTypeBySeqModel
id: number | string;//Generated by GetModelFieldType
name: string;//Generated by GetModelFieldType
slug: string;
createdAt: string;
updatedAt: string;
  
  
  
}

//The keys after the updatedAt is generated by GetAllRelatedModelNameBySeqModel - RelatedModelName
export interface StatusFormikShape extends Omit<StatusModel, "slug" | "createdAt" | "updatedAt" 
 
> {
  touched: boolean;
  index: number;
}

//Use for continuos list form
export interface StatusFormikInitialValues {
  Status: StatusFormikShape[];
  
}

//The FormikInitialValues is generated by GetAllRelatedFormikInitialValues - ModelFormikInitialValue
export interface StatusFormFormikInitialValues
  extends Omit<StatusFormikShape, "touched" | "index"> {
  
}

//The extends portion is generated by GetModelUpdatePayloadExtension - GetRelatedPartialPayload
export interface StatusUpdatePayload  {
  Status: Omit<StatusFormikShape, "touched">[];
  
}

export interface StatusDeletePayload {
  deletedStatus: string[] | number[];
}

//Use for single form (with children)
//The Related Models will be replaced by the Payload version
export interface StatusFormUpdatePayload
  extends Omit<StatusFormikShape, "touched" | "index" 
> 
 
{
  
}

export interface StatusFormikFilter {
  //Generated by GetAllFilterInterfaceBySeqmodel
q: string
}

export interface StatusSearchParams
  extends ListQuery,
    Omit<StatusFormikFilter, ""> {
  //Generated by GetAllNonStringFilterTypes

}

export interface GetStatusResponse {
  count: number;
  rows: StatusModel[];
  cursor: string;
}
