//Generated by WriteToModelinterface_ts - ModelInterface.ts Next 13


import { ListQuery } from "./interface";

export interface TrackingStatusModel {
  //Generated by GetAllModelFieldTypeBySeqModel
id: number | string;//Generated by GetModelFieldType
name: string;//Generated by GetModelFieldType
slug: string;
createdAt: string;
updatedAt: string;
  
  
  
}

//The keys after the updatedAt is generated by GetAllRelatedModelNameBySeqModel - RelatedModelName
export interface TrackingStatusFormikShape extends Omit<TrackingStatusModel, "slug" | "createdAt" | "updatedAt" 
 
> {
  touched: boolean;
  index: number;
}

//Use for continuos list form
export interface TrackingStatusFormikInitialValues {
  TrackingStatus: TrackingStatusFormikShape[];
  
}

//The FormikInitialValues is generated by GetAllRelatedFormikInitialValues - ModelFormikInitialValue
export interface TrackingStatusFormFormikInitialValues
  extends Omit<TrackingStatusFormikShape, "touched" | "index"> {
  
}

//The extends portion is generated by GetModelUpdatePayloadExtension - GetRelatedPartialPayload
export interface TrackingStatusUpdatePayload  {
  TrackingStatus: Omit<TrackingStatusFormikShape, "touched">[];
  
}

export interface TrackingStatusDeletePayload {
  deletedTrackingStatus: string[] | number[];
}

//Use for single form (with children)
//The Related Models will be replaced by the Payload version
export interface TrackingStatusFormUpdatePayload
  extends Omit<TrackingStatusFormikShape, "touched" | "index" 
> 
 
{
  
}

export interface TrackingStatusFormikFilter {
  //Generated by GetAllFilterInterfaceBySeqmodel
q: string
}

export interface TrackingStatusSearchParams
  extends ListQuery,
    Omit<TrackingStatusFormikFilter, ""> {
  //Generated by GetAllNonStringFilterTypes

}

export interface GetTrackingStatusResponse {
  count: number;
  rows: TrackingStatusModel[];
  cursor: string;
}
