//Generated by GenerateModelSyncRoute
import { NextResponse } from "next/server";
import { SessionSync } from "../../../../models/SessionModel";

export async function GET(request: Request) {
  await SessionSync();
  return NextResponse.json({ data: "success" });
}
