//Generated by GetCompleteNextAuthModelFile
import { models } from "@auth/sequelize-adapter";
import {
  CreationOptional,
  DataTypes,
  InferAttributes,
  InferCreationAttributes,
  Model,
} from "sequelize";
import sequelize from "../config/db";
//Generated by GetRelationshipImports

export default interface Account
  extends Model<InferAttributes<Account>, InferCreationAttributes<Account>> {
  id: CreationOptional<string>;
  type: string;
  provider: string;
  providerAccountId: string;
  refresh_token?: string;
  access_token?: string;
  expires_at?: number;
  token_type?: string;
  scope?: string;
  id_token?: string;
  session_state?: string;
  userId: string;
  createdAt?: Date;
  updatedAt?: Date;
}

export const Account = sequelize.define<Account>(
  "account",
  {
    ...models.Account,
    //Generated by GetModelFieldsDictionary
  },
  {
    name: { singular: "Account", plural: "Accounts" },
    tableName: "accounts",
  }
);

//Generated by GetRelationshipDeclarations

export const AccountSync = async () => {
  try {
    await Account.sync({ alter: true });
    console.log("Account table has been created!");
  } catch (error) {
    console.error(`Unable to create ${"Account".toLowerCase()} table:`, error);
  }
};
