//Generated by ImportCompleteModelFile
//Generated by GetCompleteModelFile

//Generated by GetModelImports
import {CreationOptional,DataTypes,InferAttributes,InferCreationAttributes,Model,Sequelize} from "sequelize";
import sequelize from "../config/db";
import slugify from "slugify";

//Generated by GetModelInterface
export default interface Division extends Model<InferAttributes<Division>, InferCreationAttributes<Division>>
{id: CreationOptional<number>;
name: string;
slug : CreationOptional<string>;
createdAt: CreationOptional<Date>;
updatedAt: CreationOptional<Date>}

//Generated by GetModelDefinition
export const Division = sequelize.define<Division>(
"Division",
//Generated by GetModelFieldsDictionary
{
 id: {
  type: DataTypes.BIGINT,
  autoIncrement: true,
  primaryKey: true,
  field: "id"
 }
 ,
 name: {
  type: DataTypes.STRING(50),
  unique: true,
  field: "name"
 }
 ,
 slug: {
  type: DataTypes.STRING,
  unique: true
 }
 ,
 createdAt: {
  type: DataTypes.DATE,
  defaultValue: Sequelize.literal("CURRENT_TIMESTAMP"),
  field: "createdAt"
 },
 updatedAt: {
  type: DataTypes.DATE,
  defaultValue: Sequelize.literal("CURRENT_TIMESTAMP"),
  field: "updatedAt"
 }}
,
//Generated By GetModelOptionDict
{
  name: {singular: "Division",plural:"Divisions"},
  tableName: "divisions"
}
);

//Generated by GetModelHooks
Division.beforeCreate((Division: Division, options) => {
  Division.slug = slugify(Division.name, {
    lower: true,
    remove: /[*+~.()'"!:@]/g,
    replacement: "-",
  });
});

Division.beforeUpdate((Division: Division, options) => {
  Division.slug = slugify(Division.name, {
    lower: true,
    remove: /[*+~.()'"!:@]/g,
    replacement: "-",
  });
});

//Generated by GenerateSyncModel
export const DivisionSync = async () => {
  try {
    await Division.sync({ alter: true });
    console.log("Division table has been created!");
  } catch (error) {
    console.error(
      `Unable to create ${"Division".toLowerCase()} table:`,
      error
    );
  }
};
