//Generated by ImportCompleteModelFile
//Generated by GetCompleteModelFile

//Generated by GetModelImports
import {CreationOptional,DataTypes,InferAttributes,InferCreationAttributes,Model,Sequelize} from "sequelize";
import sequelize from "../config/db";
import slugify from "slugify";

//Generated by GetModelInterface
export default interface EmployerOffice extends Model<InferAttributes<EmployerOffice>, InferCreationAttributes<EmployerOffice>>
{id: CreationOptional<number>;
name: string;
slug : CreationOptional<string>;
createdAt: CreationOptional<Date>;
updatedAt: CreationOptional<Date>}

//Generated by GetModelDefinition
export const EmployerOffice = sequelize.define<EmployerOffice>(
"EmployerOffice",
//Generated by GetModelFieldsDictionary
{
 id: {
  type: DataTypes.BIGINT,
  autoIncrement: true,
  primaryKey: true,
  field: "id"
 }
 ,
 name: {
  type: DataTypes.STRING(50),
  unique: true,
  field: "name"
 }
 ,
 slug: {
  type: DataTypes.STRING,
  unique: true
 }
 ,
 createdAt: {
  type: DataTypes.DATE,
  defaultValue: Sequelize.literal("CURRENT_TIMESTAMP"),
  field: "createdAt"
 },
 updatedAt: {
  type: DataTypes.DATE,
  defaultValue: Sequelize.literal("CURRENT_TIMESTAMP"),
  field: "updatedAt"
 }}
,
//Generated By GetModelOptionDict
{
  name: {singular: "EmployerOffice",plural:"EmployerOffices"},
  tableName: "employer_offices"
}
);

//Generated by GetModelHooks
EmployerOffice.beforeCreate((EmployerOffice: EmployerOffice, options) => {
  EmployerOffice.slug = slugify(EmployerOffice.name, {
    lower: true,
    remove: /[*+~.()'"!:@]/g,
    replacement: "-",
  });
});

EmployerOffice.beforeUpdate((EmployerOffice: EmployerOffice, options) => {
  EmployerOffice.slug = slugify(EmployerOffice.name, {
    lower: true,
    remove: /[*+~.()'"!:@]/g,
    replacement: "-",
  });
});

//Generated by GenerateSyncModel
export const EmployerOfficeSync = async () => {
  try {
    await EmployerOffice.sync({ alter: true });
    console.log("Employer Office table has been created!");
  } catch (error) {
    console.error(
      `Unable to create ${"Employer Office".toLowerCase()} table:`,
      error
    );
  }
};
