//Generated by ImportCompleteModelFile
//Generated by GetCompleteModelFile

//Generated by GetModelImports
import {CreationOptional,DataTypes,InferAttributes,InferCreationAttributes,Model,Sequelize} from "sequelize";
import sequelize from "../config/db";
import slugify from "slugify";

//Generated by GetModelInterface
export default interface PlacementStatus extends Model<InferAttributes<PlacementStatus>, InferCreationAttributes<PlacementStatus>>
{id: CreationOptional<number>;
name: string;
slug : CreationOptional<string>;
createdAt: CreationOptional<Date>;
updatedAt: CreationOptional<Date>}

//Generated by GetModelDefinition
export const PlacementStatus = sequelize.define<PlacementStatus>(
"PlacementStatus",
//Generated by GetModelFieldsDictionary
{
 id: {
  type: DataTypes.BIGINT,
  autoIncrement: true,
  primaryKey: true,
  field: "id"
 }
 ,
 name: {
  type: DataTypes.STRING(50),
  unique: true,
  field: "name"
 }
 ,
 slug: {
  type: DataTypes.STRING,
  unique: true
 }
 ,
 createdAt: {
  type: DataTypes.DATE,
  defaultValue: Sequelize.literal("CURRENT_TIMESTAMP"),
  field: "createdAt"
 },
 updatedAt: {
  type: DataTypes.DATE,
  defaultValue: Sequelize.literal("CURRENT_TIMESTAMP"),
  field: "updatedAt"
 }}
,
//Generated By GetModelOptionDict
{
  name: {singular: "PlacementStatus",plural:"PlacementStatus"},
  tableName: "placement_status"
}
);

//Generated by GetModelHooks
PlacementStatus.beforeCreate((PlacementStatus: PlacementStatus, options) => {
  PlacementStatus.slug = slugify(PlacementStatus.name, {
    lower: true,
    remove: /[*+~.()'"!:@]/g,
    replacement: "-",
  });
});

PlacementStatus.beforeUpdate((PlacementStatus: PlacementStatus, options) => {
  PlacementStatus.slug = slugify(PlacementStatus.name, {
    lower: true,
    remove: /[*+~.()'"!:@]/g,
    replacement: "-",
  });
});

//Generated by GenerateSyncModel
export const PlacementStatusSync = async () => {
  try {
    await PlacementStatus.sync({ alter: true });
    console.log("Placement Status table has been created!");
  } catch (error) {
    console.error(
      `Unable to create ${"Placement Status".toLowerCase()} table:`,
      error
    );
  }
};
