//Generated by WriteToModelsPage - Model Page Sidebar
import React from "react";
import PriorityFilterForm from "@/components/priorities/PriorityFilterForm";
import PriorityTable from "@/components/priorities/PriorityTable";

export const metadata = {
  title: "Priorities",
};

const Priorities: React.FC = () => {
  return (
    <div className="flex flex-col flex-1 w-full px-4 mx-auto text-sm lg:px-0 main-height-less-footer">
      <div className="flex flex-col flex-1 w-[740px] mx-auto gap-4 p-4 border rounded-sm border-border">
        <h1 className="text-2xl font-bold">Priorities</h1>
        <div className="flex">
          <PriorityFilterForm />
        </div>
        <div className="flex flex-col flex-1 ">
          <PriorityTable />
        </div>
      </div>
    </div>
  );
};

export default Priorities;
