//Generated by GenerateModelSyncRoute
import { NextResponse } from "next/server";
import { AccountSync } from "../../../../models/AccountModel";

export async function GET(request: Request) {
  await AccountSync();
  return NextResponse.json({ data: "success" });
}
