//Generated by WriteToMultiRoute_ts - multi route.ts
import sequelize from "@/config/db";
import { createStage, updateStage } from "@/utils/api/StageLibs";
import { StageUpdatePayload } from "@/interfaces/StageInterfaces";
import { StageSchema } from "@/schema/StageSchema";
import { PRIMARY_KEY, UNIQUE_FIELDS } from "@/utils/constants/StageConstants";
import handleSequelizeError from "@/utils/errorHandling";
import { checkDuplicateCombinations, returnJSONResponse } from "@/utils/utils";
import { NextResponse } from "next/server";

//Generated by GetMultiCreateModelPOSTRoute - GetMultiCreateModelPOSTRoute
export const POST = async (req: Request) => {
  const body = (await req.json()) as StageUpdatePayload;
  const { Stages } = body;

  //Generated by GenerateUniquenessValidation
  //Validate record uniqueness

  UNIQUE_FIELDS.forEach((item) => {
    const uniquenessError = checkDuplicateCombinations(item, Stages);

    if (uniquenessError) {
      return returnJSONResponse({
        status: "error",
        error: uniquenessError,
        errorCode: 422,
      });
    }
  });

  const t = await sequelize.transaction();
  let recordsCreated = 0;

  for (const item of Stages) {
    try {
      await StageSchema.validate(item);
    } catch (error) {
      return handleSequelizeError(error);
    }
  }

  try {
    for (const item of Stages) {
      if (item[PRIMARY_KEY] === "") {
        await createStage(item, t);
        recordsCreated++;
      } else {
        await updateStage(item, PRIMARY_KEY, t);
      }
    }

    await t.commit();

    return NextResponse.json({
      recordsCreated,
    });
  } catch (err) {
    await t.rollback();
    return handleSequelizeError(err);
  }
};;
