//Generated by GetuseModelListts - useModelList.ts
"use client";
import { GetProviderSourcesResponse } from "@/interfaces/ProviderSourceInterfaces";
import { ProviderSourceSearchParams } from "@/interfaces/ProviderSourceInterfaces";
import { BasicModel } from "@/interfaces/GeneralInterfaces";
import axiosClient from "@/utils/api";
import { useQuery } from "@tanstack/react-query";
import { useEffect, useState } from "react";

const getProviderSources = async () => {
  const { data } = await axiosClient.get<GetProviderSourcesResponse>(`provider-sources`, {
    params: {
      fetchCount: "false",
      simpleOnly: "true",
    } as Partial<ProviderSourceSearchParams>,
  });

  return data.rows.map((item) => ({
    id: item.id,
    name: item.name,
  }));
};

interface UseListProps {
  placeholderData?: BasicModel[];
}

const useProviderSourceList = (prop?: UseListProps) => {
  //local states
  const [mounted, setMounted] = useState(false);

  const _ = useQuery({
    queryKey: ["providerSource-list"],
    queryFn: getProviderSources,
    enabled: mounted,
    placeholderData: prop?.placeholderData,
  });

  useEffect(() => {
    setMounted(true);
  }, []);

  return _;
};

export default useProviderSourceList;
