//Generated by WriteToModelschema_ts - ModelSchema.ts
import * as Yup from "yup";

const CandidateStatusSchema = Yup.object().shape({
  //Generated by GetAllFieldValidationBySeqModel
  candidateID: Yup.number().required("Candidate ID is a required field."),
  statusID: Yup.number().required("Status ID is a required field."),
});

const CandidateStatusArraySchema = Yup.object().shape({
  CandidateStatus: Yup.array().of(
    Yup.object().shape({
      //Generated by GetAllArrayFieldValidationBySeqModel
      candidateID: Yup.number().when("touched", ([touched], schema) =>
        touched
          ? schema.required("Candidate ID is a required field.")
          : schema.notRequired()
      ),
      statusID: Yup.number().when("touched", ([touched], schema) =>
        touched
          ? schema.required("Status ID is a required field.")
          : schema.notRequired()
      ),
    })
  ),
});

export { CandidateStatusSchema, CandidateStatusArraySchema };
